### ISSUE TITLE
Shorter BF file

### ISSUE THREAD

**Issue by RysteQ** [CodesterClub/BFuck-Interpreter#5]
I know this is a little stupid to ask but i already have a Hello World program for bf which is sorter and easier for a person read

Here:

<h4>++++++++++[>+++++++>++++++++++>+++>+++++++++<<<<-]>++.>+.+++++++..+++.>++.>---.<<.+++.------.--------.>+.</h4>

**Comment by CodesterClub** [comment]
Alright! We'll check it out. Did you try? Did it work on our interpreter?

EDIT: It didn't work. But thanks for the code

**Comment by RysteQ** [comment]
I tried it on another interpreter, i have made my own interpreter but it has one flaw and it is not on github, maybe one day i will re-write it and share it, thanks for taking your time to test the code !
